build = "cargo build"
test = "cargo test"
clippy-fix = "cargo clippy --fix --bin squite"
clippy = "cargo clippy"
format = "cargo fmt"
format-check = "cargo fmt --check"
version-bump = "./scripts/version_bump.py"
